# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: VPS Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: Generate app settings file
        run: node ./Scripts/env.js
        env:
          DEFAULT_CONNECTION_STRING: "${{ secrets.DEFAULT_CONNECTION_STRING }}"
          JWT_AUDIENCE: "${{ secrets.JWT_AUDIENCE }}"
          JWT_ISSUER: "${{ secrets.JWT_ISSUER }}"
          JWT_KEY: "${{ secrets.JWT_KEY }}"
          JWT_SUBJECT: "${{ secrets.JWT_SUBJECT }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Dotnet Publish
        run: dotnet publish ESM.API -c Release

      - name: Copy bundle to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./ESM.API/bin/Release/net6.0/publish/*"
          target: "/var/www/esm-be"
          strip_components: 5
